name: Build meta.json

on:
  push:
    paths:
      - "data/**"
      - "scripts/**"
      - ".github/workflows/build-meta.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build meta.json
        run: python3 scripts/build_meta.py

      - name: Commit updated meta.json
        run: |
          git config user.name "meta-bot"
          git config user.email "meta-bot@users.noreply.github.com"
          git add public/meta.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Update meta.json"
          git push
